use super::*;

impl UiCommand {
    pub(super) fn palette_spec(self) -> Option<PaletteCommandSpec> {
        match self {
            Self::ToggleFocus => Some(PaletteCommandSpec {
                id: "palette:toggle_focus",
                title: "Toggle Pane Focus",
                description: "Switch focus between workspace list and preview (Tab/h/l)",
                tags: &["tab", "h", "l", "focus", "pane"],
                category: "Navigation",
            }),
            Self::ToggleSidebar => Some(PaletteCommandSpec {
                id: "palette:toggle_sidebar",
                title: "Toggle Sidebar",
                description: "Show or hide workspace sidebar (\\)",
                tags: &["sidebar", "layout", "\\", "toggle"],
                category: "Navigation",
            }),
            Self::OpenPreview => Some(PaletteCommandSpec {
                id: "palette:open_preview",
                title: "Open Preview",
                description: "Focus preview pane, launch shell preview when needed (Enter/l)",
                tags: &["open", "preview", "enter", "l"],
                category: "List",
            }),
            Self::EnterInteractive => Some(PaletteCommandSpec {
                id: "palette:enter_interactive",
                title: "Enter Interactive Mode",
                description: "Attach to selected preview session (agent, shell, or lazygit) (Enter)",
                tags: &[
                    "interactive",
                    "attach",
                    "shell",
                    "agent",
                    "lazygit",
                    "enter",
                ],
                category: "Preview",
            }),
            Self::FocusPreview | Self::OpenCommandPalette => None,
            Self::FocusList => Some(PaletteCommandSpec {
                id: "palette:focus_list",
                title: "Focus Workspace List",
                description: "Return focus to workspace list (Esc)",
                tags: &["list", "focus", "esc"],
                category: "Navigation",
            }),
            Self::MoveSelectionUp => Some(PaletteCommandSpec {
                id: "palette:move_selection_up",
                title: "Select Previous Workspace",
                description: "Move workspace selection up (k / Up)",
                tags: &["up", "previous", "workspace", "k"],
                category: "List",
            }),
            Self::MoveSelectionDown => Some(PaletteCommandSpec {
                id: "palette:move_selection_down",
                title: "Select Next Workspace",
                description: "Move workspace selection down (j / Down)",
                tags: &["down", "next", "workspace", "j"],
                category: "List",
            }),
            Self::ScrollUp => Some(PaletteCommandSpec {
                id: "palette:scroll_up",
                title: "Scroll Up",
                description: "Scroll preview output up (k / Up)",
                tags: &["scroll", "up", "k"],
                category: "Preview",
            }),
            Self::ScrollDown => Some(PaletteCommandSpec {
                id: "palette:scroll_down",
                title: "Scroll Down",
                description: "Scroll preview output down (j / Down)",
                tags: &["scroll", "down", "j"],
                category: "Preview",
            }),
            Self::PageUp => Some(PaletteCommandSpec {
                id: "palette:page_up",
                title: "Page Up",
                description: "Scroll preview up by one page (PgUp)",
                tags: &["pageup", "pgup", "scroll"],
                category: "Preview",
            }),
            Self::PageDown => Some(PaletteCommandSpec {
                id: "palette:page_down",
                title: "Page Down",
                description: "Scroll preview down by one page (PgDn)",
                tags: &["pagedown", "pgdn", "scroll"],
                category: "Preview",
            }),
            Self::ScrollBottom => Some(PaletteCommandSpec {
                id: "palette:scroll_bottom",
                title: "Jump To Bottom",
                description: "Jump preview output to bottom (G / End)",
                tags: &["bottom", "latest", "G", "End"],
                category: "Preview",
            }),
            Self::PreviousTab => Some(PaletteCommandSpec {
                id: "palette:previous_tab",
                title: "Previous Preview Tab",
                description: "Switch to previous preview tab ([)",
                tags: &["previous", "tab", "[", "agent", "git"],
                category: "Navigation",
            }),
            Self::NextTab => Some(PaletteCommandSpec {
                id: "palette:next_tab",
                title: "Next Preview Tab",
                description: "Switch to next preview tab (])",
                tags: &["next", "tab", "]", "agent", "git"],
                category: "Navigation",
            }),
            Self::NewWorkspace => Some(PaletteCommandSpec {
                id: "palette:new_workspace",
                title: "New Workspace",
                description: "Open workspace creation dialog (n)",
                tags: &["new", "workspace", "create", "n"],
                category: "Workspace",
            }),
            Self::EditWorkspace => Some(PaletteCommandSpec {
                id: "palette:edit_workspace",
                title: "Edit Workspace",
                description: "Open workspace edit dialog (agent + base branch) (e)",
                tags: &["edit", "workspace", "agent", "base", "branch", "e"],
                category: "Workspace",
            }),
            Self::StartAgent => Some(PaletteCommandSpec {
                id: "palette:start_agent",
                title: "Start Agent",
                description: "Open start-agent dialog for selected workspace (s)",
                tags: &["start", "agent", "workspace", "s"],
                category: "Workspace",
            }),
            Self::StopAgent => Some(PaletteCommandSpec {
                id: "palette:stop_agent",
                title: "Stop Agent",
                description: "Stop selected workspace agent (x)",
                tags: &["stop", "agent", "workspace", "x"],
                category: "Workspace",
            }),
            Self::DeleteWorkspace => Some(PaletteCommandSpec {
                id: "palette:delete_workspace",
                title: "Delete Workspace",
                description: "Open delete dialog for selected workspace (D)",
                tags: &["delete", "workspace", "worktree", "D"],
                category: "Workspace",
            }),
            Self::MergeWorkspace => Some(PaletteCommandSpec {
                id: "palette:merge_workspace",
                title: "Merge Workspace",
                description: "Merge selected workspace branch into base (m)",
                tags: &["merge", "workspace", "branch", "m"],
                category: "Workspace",
            }),
            Self::UpdateFromBase => Some(PaletteCommandSpec {
                id: "palette:update_from_base",
                title: "Update From Base",
                description: "Merge base branch into selected workspace (u)",
                tags: &["update", "sync", "base", "workspace", "u"],
                category: "Workspace",
            }),
            Self::OpenProjects => Some(PaletteCommandSpec {
                id: "palette:open_projects",
                title: "Projects",
                description: "Open project switcher dialog (p)",
                tags: &["projects", "project", "switcher", "p"],
                category: "Workspace",
            }),
            Self::DeleteProject => Some(PaletteCommandSpec {
                id: "palette:delete_project",
                title: "Remove Selected Project",
                description: "Remove selected workspace project (Ctrl+X/Del)",
                tags: &[
                    "remove",
                    "delete",
                    "project",
                    "workspace list",
                    "ctrl+x",
                    "del",
                ],
                category: "Workspace",
            }),
            Self::OpenSettings => Some(PaletteCommandSpec {
                id: "palette:open_settings",
                title: "Settings",
                description: "Open settings dialog (S)",
                tags: &["settings", "multiplexer", "S"],
                category: "Workspace",
            }),
            Self::ToggleUnsafe => Some(PaletteCommandSpec {
                id: "palette:toggle_unsafe",
                title: "Toggle Unsafe Launch",
                description: "Toggle launch skip-permissions default (!)",
                tags: &["unsafe", "permissions", "!"],
                category: "Workspace",
            }),
            Self::OpenHelp => Some(PaletteCommandSpec {
                id: "palette:open_help",
                title: "Keybind Help",
                description: "Open keyboard shortcut help (?)",
                tags: &["help", "shortcuts", "?"],
                category: "System",
            }),
            Self::Quit => Some(PaletteCommandSpec {
                id: "palette:quit",
                title: "Quit Grove",
                description: "Exit application (q)",
                tags: &["quit", "exit", "q"],
                category: "System",
            }),
        }
    }
}
